version: "3.4"

services:
  transitservice:
    image: transitservice
    container_name: transitservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      PORT: 8105
    ports:
      - 8105:8105
    networks:
      ioak-net:
        aliases:
          - transitservice.docker

networks:
  ioak-net:
